name: 'Get and cache the dependencies'
description: 'Get the dependencies and cache them (via npm)'
runs:
  using: composite
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json' )}}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash